# Shell variables
# Generated by 'wal'
wallpaper='/home/bocho/Pictures/wallpaper-1.png'

# Special
background='#070808'
foreground='#bfc3c6'
cursor='#bfc3c6'

# Colors
color0='#070808'
color1='#464E58'
color2='#4D5966'
color3='#5D6774'
color4='#A26D60'
color5='#6D7985'
color6='#79858F'
color7='#bfc3c6'
color8='#85888a'
color9='#464E58'
color10='#4D5966'
color11='#5D6774'
color12='#A26D60'
color13='#6D7985'
color14='#79858F'
color15='#bfc3c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
