--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bocho/Pictures/wallpaper-1.png"

-- Special
background="#070808"
foreground="#bfc3c6"
cursor="#bfc3c6"

-- Colors
color0="#070808"
color1="#464E58"
color2="#4D5966"
color3="#5D6774"
color4="#A26D60"
color5="#6D7985"
color6="#79858F"
color7="#bfc3c6"
color8="#85888a"
color9="#464E58"
color10="#4D5966"
color11="#5D6774"
color12="#A26D60"
color13="#6D7985"
color14="#79858F"
color15="#bfc3c6"
